version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./docker/.env
    volumes:
      - .:/pms_server
    ports:
      - "3000:3000"
    depends_on:
      - db
