version: '3'
services:
  mongodb:
    image: mongo:4.2.0-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./docker/.env
    volumes:
      - .:/pms_server
    ports:
      - "3000:3000"
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  mongo: